# Generated by Django 4.2.2 on 2023-06-11 16:18

import asset.enums
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
            bases=('asset.basemodel',),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=150)),
                ('license_type', models.CharField(choices=[('licença comercial', 'licença comercial'), ('licença de código aberto', 'licença de código aberto'), ('licença de avaliação', 'licença de avaliação')], default=asset.enums.LicenceType['COMERCIAL'], max_length=24)),
                ('acquisition_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='asset.supplier')),
            ],
            bases=('asset.basemodel',),
        ),
    ]
