# Generated by Django 4.2.2 on 2023-07-07 22:16

import asset.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Em operação', 'Em operação'), ('Fora de uso', 'Fora de uso'), ('Expirado', 'Expirado')], default=asset.enums.AssetStatus['ACTIVE'], max_length=11),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Em avaliação', 'Em avaliação'), ('Encerrado', 'Encerrado'), ('Em negociação', 'Em negociação')], default=asset.enums.SupplierStatus['REVIEW'], max_length=13),
        ),
    ]
