# Generated by Django 4.2.2 on 2023-09-25 18:48

import asset.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_asset_status_supplier_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='asset.basemodel')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Em avaliação', 'Em avaliação'), ('Encerrado', 'Encerrado'), ('Em negociação', 'Em negociação')], default=asset.enums.SupplierStatus['REVIEW'], max_length=13)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical supplier',
                'verbose_name_plural': 'historical suppliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('basemodel_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='asset.basemodel')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=150)),
                ('license_type', models.CharField(choices=[('licença comercial', 'licença comercial'), ('licença de código aberto', 'licença de código aberto'), ('licença de avaliação', 'licença de avaliação')], default=asset.enums.LicenceType['COMERCIAL'], max_length=24)),
                ('acquisition_date', models.DateTimeField(blank=True, editable=False)),
                ('expiration_date', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Em operação', 'Em operação'), ('Fora de uso', 'Fora de uso'), ('Expirado', 'Expirado')], default=asset.enums.AssetStatus['ACTIVE'], max_length=11)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.supplier')),
            ],
            options={
                'verbose_name': 'historical asset',
                'verbose_name_plural': 'historical assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
