# Generated by Django 4.2.2 on 2023-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_historicalsupplier_historicalasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
